apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-pv
  namespace: prod
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.0.210
    path: /storage/kafka
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-pvc
  namespace: prod
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
