apiVersion: v1
kind: Service
metadata:
  name: mvc-api-svc
  namespace: prod
spec:
  selector:
    app: mvc-api
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
