apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-dep
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
        - name: consumer-pod
          image: ghcr.io/ukjjang/any-community/prod/consumer:202412290309-48f1e1b
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: consumer-cm
      imagePullSecrets:
        - name: ghcr-secret
