apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-dep
  namespace: prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
        - name: consumer-pod
          image: ghcr.io/ukjjang/any-community/prod/consumer:202501091150-24fcfb6
          ports:
            - containerPort: 8090
          envFrom:
            - configMapRef:
                name: consumer-cm
          resources:
            requests:
              cpu: 50m
              memory: 200Mi
            limits:
              cpu: 100m
              memory: 400Mi
      imagePullSecrets:
        - name: ghcr-secret
