apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-dep
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
        - name: consumer-pod
          image: ghcr.io/ukjjang/any-community/prod/consumer:202501120139-feb1a7b
          ports:
            - containerPort: 8090
          envFrom:
            - configMapRef:
                name: consumer-cm
#          resources:
#            requests:
#              cpu: 50m
#              memory: 200Mi
#            limits:
#              cpu: 100m
#              memory: 400Mi
      imagePullSecrets:
        - name: ghcr-secret
