apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-dep
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
        - name: consumer-pod
          image: ghcr.io/ukjjang/any-community/prod/consumer:202501120213-f9c65cc
          ports:
            - containerPort: 8090
          envFrom:
            - configMapRef:
                name: consumer-cm
          resources:
            requests:
              cpu: 100m
              memory: 500Mi
            limits:
              cpu: 200m
              memory: 1Gi
      imagePullSecrets:
        - name: ghcr-secret
