apiVersion: v1
kind: Service
metadata:
  name: consumer-svc
  namespace: prod
spec:
  selector:
    app: consumer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8090
  type: ClusterIP
