apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarqube-dep
  namespace: sonarqube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarqube
  template:
    metadata:
      labels:
        app: sonarqube
    spec:
      containers:
        - name: sonarqube
          image: sonarqube:lts
          ports:
            - containerPort: 9000
          volumeMounts:
            - mountPath: /opt/sonarqube/data
              name: sonarqube-data
#          resources:
#            requests:
#              cpu: 100m
#              memory: 256Mi
#            limits:
#              cpu: 200m
#              memory: 512Mi
      volumes:
        - name: sonarqube-data
          persistentVolumeClaim:
            claimName: sonarqube-pvc
