apiVersion: apps/v1
kind: Deployment
metadata:
  name: mvc-api-dep
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mvc-api
  template:
    metadata:
      labels:
        app: mvc-api
    spec:
      containers:
        - name: mvc-api-pod
          image: ghcr.io/ukjjang/any-community/prod/mvc-api:202501120211-f9c65cc
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: mvc-api-cm
          resources:
            requests:
              cpu: 100m
              memory: 500Mi
            limits:
              cpu: 200m
              memory: 1Gi
      imagePullSecrets:
        - name: ghcr-secret
