apiVersion: apps/v1
kind: Deployment
metadata:
  name: mvc-api-dep
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mvc-api
  template:
    metadata:
      labels:
        app: mvc-api
    spec:
      containers:
        - name: mvc-api-pod
          image: ghcr.io/ukjjang/any-community/prod/mvc-api:202412281217-6baec15
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: mvc-api-cm
      imagePullSecrets:
        - name: ghcr-secret
