apiVersion: v1
kind: PersistentVolume
metadata:
  name: zookeeper-pv
  namespace: prod
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.0.210
    path: /storage/zookeeper
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zookeeper-pvc
  namespace: prod
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
